### ISSUE TITLE
[Feature Request] add Traefik

### ISSUE THREAD

**Issue by greggameplayer** [SensorsIot/IOTstack#160]
It would be good to add the so called Traefik

**Comment by robertcsakany** [comment]
+1 From next week I will have time. I've already planned several weeks ago to add traefik support to be able to proxy ports other than HTTP.

**Comment by robertcsakany** [comment]
I have some working prototype in a docker compose file which can do the following things:
 - All web containers proxied over traefik - means subdomans / URL's can be used
 - Automatic Let's encrypt management - means the proxy over HTTPS
 - SSO Single SignOn with Google - means the management pages can be accessed from outside, but protected with login.
 - Samba image added - so configurations can be edited from my desktop machine without any magic outside IOTStack :) - I make some PR today for that.

Please guys check it. Have to discuss how can be integrated to current templates - @Slyke ?

```
version: '3.3'

networks:
  inbound:
    driver: bridge
  internal:
    driver: bridge

services:

# #############################################################################
# #############################################################################

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data
    networks:
      - inbound
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inbound"

      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.portainer.middlewares=secured"

      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.portainer-secure.tls.certresolver=tls"
      - "traefik.http.routers.portainer-secure.middlewares=secured"

      - "traefik.http.routers.portainer-secure.service=portainer-secure"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9000"


# #############################################################################
# #############################################################################

  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    env_file: ./services/nodered/nodered.env
    ports:
      - target: 1880
        published: 1880
        mode: host
    volumes:
      - ./volumes/nodered/data:/data
    depends_on:
      - mosquitto
    networks:
      - internal
      - inbound
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inbound"

      - "traefik.http.routers.nodered.entrypoints=http"
      - "traefik.http.routers.nodered.rule=Host(`nodered.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.nodered.middlewares=secured"

      - "traefik.http.routers.nodered-secure.entrypoints=https"
      - "traefik.http.routers.nodered-secure.rule=Host(`nodered.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.nodered-secure.tls.certresolver=tls"
      - "traefik.http.routers.nodered-secure.middlewares=secured"

      - "traefik.http.routers.nodered-secure.service=nodered-secure"
      - "traefik.http.services.nodered-secure.loadbalancer.server.port=1880"


# #############################################################################
# #############################################################################

  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - target: 8086
        published: 8086
        mode: host
      - target: 8083
        published: 8083
        mode: host
      - target: 2003
        published: 2003
        mode: host
    env_file:
      - ./services/influxdb/influxdb.env
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./backups/influxdb/db:/var/lib/influxdb/backup
    networks:
      - internal

# #############################################################################
# #############################################################################

  grafana:
    container_name: grafana
    image: grafana/grafana:6.3.6
    restart: unless-stopped
    user: "0"
    ports:
      - target: 3000
        published: 3000
        mode: host
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
    networks:
      - internal
      - inbound
    labels:

      - "traefik.enable=true"
      - "traefik.docker.network=inbound"

      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.grafana.middlewares=secured"

      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.grafana-secure.tls.certresolver=tls"
      - "traefik.http.routers.grafana-secure.middlewares=secured"

      - "traefik.http.routers.grafana-secure.service=grafana-secure"
      - "traefik.http.services.grafana-secure.loadbalancer.server.port=3000"

# #############################################################################
# #############################################################################

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "1883"
    ports:
      - target: 1883
        published: 1883
        mode: host
      - target: 9001
        published: 9001
        mode: host
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - internal

# #############################################################################
# #############################################################################

  telegraf:
    container_name: telegraf
    image: telegraf
    restart: unless-stopped
    volumes:
      - ./services/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    networks:
      - internal

# #############################################################################
# #############################################################################

#  openhab:
#    image: "openhab/openhab:2.5.3"
#    container_name: openhab
#    restart: unless-stopped
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"
#      - "./volumes/openhab/addons:/openhab/addons"
#      - "./volumes/openhab/conf:/openhab/conf"
#      - "./volumes/openhab/userdata:/openhab/userdata"
#    environment:
#      OPENHAB_HTTP_PORT: "8080"
#      OPENHAB_HTTPS_PORT: "8443"
#      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
#    depends_on:
#      - mosquitto
#    ports:
#      - target: 5007
#        published: 5007
#        mode: host
#      - target: 8080
#        published: 8881
#        mode: host
#    networks:
#      - internal
#      - inbound
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.openhab.rule=Host(`openhab.<!!! YOURDOMAIN !!!>`)"
#      - "traefik.http.routers.openhab.service=openhab"
#      - "traefik.http.services.openhab.loadbalancer.server.port=8080"
#      - "traefik.http.routers.openhab.tls.certresolver=tls"
#      - "traefik.http.routers.openhab.entrypoints=https"
#      - "traefik.docker.network=inbound"
#
##    # The command node is very important. It overrides
##    # the "gosu openhab tini -s ./start.sh" command from Dockerfile and runs as root!
##    command: "tini -s ./start.sh server"

# #############################################################################
# #############################################################################

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./volumes/zigbee2mqtt/data:/app/data
    devices:
      #- /dev/ttyAMA0:/dev/ttyACM0
      #- /dev/ttyACM0:/dev/ttyACM0
      #- /dev/ttyUSB0:/dev/ttyACM0
#      - /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_09_E3-if00-port0:/dev/ttyACM0
      - /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CB_FD_A8-if00-port0:/dev/ttyACM0
    restart: unless-stopped
#    network_mode: host
    ports:
      - target: 8080
        published: 8882
        mode: host
    depends_on:
      - mosquitto
    networks:
      - internal
      - inbound
    labels:

      - "traefik.enable=true"
      - "traefik.docker.network=inbound"

      - "traefik.http.routers.zigbee2mqtt.entrypoints=http"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.zigbee2mqtt.middlewares=secured"

      - "traefik.http.routers.zigbee2mqtt-secure.entrypoints=https"
      - "traefik.http.routers.zigbee2mqtt-secure.rule=Host(`zigbee2mqtt.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.zigbee2mqtt-secure.tls.certresolver=tls"
      - "traefik.http.routers.zigbee2mqtt-secure.middlewares=secured"

      - "traefik.http.routers.zigbee2mqtt-secure.service=zigbee2mqtt-secure"
      - "traefik.http.services.zigbee2mqtt-secure.loadbalancer.server.port=8080"


# #############################################################################
# #############################################################################

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest 
    restart: unless-stopped
    ports:
      - target: 8080
        published: 8888
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - inbound
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inbound"

      - "traefik.http.routers.dozzle.entrypoints=http"
      - "traefik.http.routers.dozzle.rule=Host(`logs.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.dozzle.middlewares=secured"

      - "traefik.http.routers.dozzle-secure.entrypoints=https"
      - "traefik.http.routers.dozzle-secure.rule=Host(`logs.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.dozzle-secure.tls.certresolver=tls"
      - "traefik.http.routers.dozzle-secure.middlewares=secured"

      - "traefik.http.routers.dozzle-secure.service=dozzle-secure"
      - "traefik.http.services.dozzle-secure.loadbalancer.server.port=8080"


# #############################################################################
# #############################################################################


  aliyun-dyndns:
    container_name: aliyun-dyndns
    restart: unless-stopped
    image: sanjusss/aliyun-ddns:0.2.7-linux-arm32v7
    networks:
      - internal
    environment:
      - "TZ=Europe/Budapest"
      - "AKID=<!!! ALIDNS KEY !!!>"
      - "AKSCT=<!!! ALIDNS SECRET !!!>"
      - "DOMAIN=traefik.<!!! YOURDOMAIN !!!>,auth.<!!! YOURDOMAIN !!!>,logs.<!!! YOURDOMAIN !!!>,grafana.<!!! YOURDOMAIN !!!>,traefik.<!!! YOURDOMAIN !!!>,nodered.<!!! YOURDOMAIN !!!>,openhab.<!!! YOURDOMAIN !!!>,portainer.<!!! YOURDOMAIN !!!>,zigbee2mqtt.<!!! YOURDOMAIN !!!>"
      - "REDO=30"
      - "TTL:30"

# #############################################################################
# #############################################################################

  traefik:
    restart: unless-stopped
    network_mode: host
    depends_on:
     - aliyun-dyndns
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.tls.acme.tlschallenge=true"
      - "--certificatesresolvers.tls.acme.email=<!!! YOUR EMAIL !!!>"
      - "--certificatesresolvers.tls.acme.storage=/letsencrypt/tls-acme.json"

    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - "TZ=Europe/Budapest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/traefik/letsencrypt:/letsencrypt"
      - "./volumes/traefik/etc:/etc/traefik"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inbound"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.traefik.middlewares=secured"

      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.traefik-secure.tls.certresolver=tls"
      - "traefik.http.routers.traefik-secure.middlewares=secured"

      - "traefik.http.middlewares.secured.chain.middlewares=https-only@docker,test-auth@docker"

      - "traefik.http.middlewares.https-only.redirectscheme.scheme=https"

      - "traefik.http.middlewares.test-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.test-auth.forwardauth.Address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.test-auth.forwardauth.authResponseHeaders=X-Forwarded-User, X-WebAuth-User"

      - "traefik.http.routers.traefik-secure.service=traefik-secure"
      - "traefik.http.services.traefik-secure.loadbalancer.server.port=8080"


# #############################################################################
# #############################################################################

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2-arm
    container_name: traefik-forward-auth
    restart:  unless-stopped
    ports:
      - target: 4181
        published: 4181
        protocol: tcp
        mode: host

    networks:
      - internal
      - inbound
    environment:
      - "PROVIDERS_GOOGLE_CLIENT_ID=<!!! GOOLE OAUTH API CLIENT ID !!!>"
      - "PROVIDERS_GOOGLE_CLIENT_SECRET=<!!! GOOLE OAUTH API CLIENT SECRET !!!>"
      - "SECRET=<!!! SOME GENERATED SECET !!!>"
      - "COOKIE_DOMAIN=<!!! YOURDOMAIN !!!>"
      - "INSECURE_COOKIE=false"
      - "AUTH_HOST=auth.<!!! YOURDOMAIN !!!>"
      - "URL_PATH=/_oauth"
      - "WHITELIST=<!!! YOUR ACCEPTED EMAIL 1 !!!>,<!!! YOUR ACCEPTED EMAIL 2 !!!>,<!!! YOUR ACCEPTED EMAIL 3 !!!>"
      - "TZ=Europe/Budapest"
      - "LOG_LEVEL=debug"
      - "LOG_FORMAT=text"
      - "LIFETIME=2592000"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inbound"
      - "traefik.http.routers.traefik-forward-auth.entrypoints=http"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.<!!! YOURDOMAIN !!!>`)"

      - "traefik.http.routers.traefik-forward-auth-secure.entrypoints=https"
      - "traefik.http.routers.traefik-forward-auth-secure.rule=Host(`auth.<!!! YOURDOMAIN !!!>`)"
      - "traefik.http.routers.traefik-forward-auth-secure.tls.certresolver=tls"
      - "traefik.http.routers.traefik-forward-auth-secure.middlewares=secured"

      - "traefik.http.middlewares.secured.chain.middlewares=https-only@docker,test-auth@docker"

      - "traefik.http.middlewares.https-only.redirectscheme.scheme=https"

      - "traefik.http.middlewares.test-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.test-auth.forwardauth.Address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.test-auth.forwardauth.authResponseHeaders=X-Forwarded-User, X-WebAuth-User"

      - "traefik.http.routers.traefik-forward-auth-secure.service=traefik-forward-auth-secure"
      - "traefik.http.services.traefik-forward-auth-secure.loadbalancer.server.port=4181"

# #############################################################################
# #############################################################################

  samba:
    image: dperson/samba:latest
    container_name: samba
    restart:  unless-stopped
    environment:
      - TZ=Europe/Budapest
    networks:
      - internal
    ports:
      - target: 137
        published: 137
        mode: host
        protocol: udp
      - target: 138
        published: 138
        mode: host
        protocol: udp
      - target: 139
        published: 139
        mode: host
        protocol: tcp
      - target: 445
        published: 445
        mode: host
        protocol: tcp
    read_only: true
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - ./:/mnt:z
    command: '-s "IOT Stack;/mnt;yes;no;no;iot" -u "iot;iot" -p'

```
