### ISSUE TITLE
[experimental branch] Nextcloud Database Password Options causes bug in docker-compose.yml

### ISSUE THREAD

**Issue by JoeyDodson** [SensorsIot/IOTstack#176]
When I was testing the experimental branch, I discovered a bug with the Database Password Options for Nextcloud. When choosing the option 'Randomise passwords every build', the `docker-compose.yml` file gets built without the `nextcloud_db` service included. 

EDIT: After further testing I now believe running the `Options` menu at all causes this bug, even if I select other options there (including `Use default...`).

When running `docker-compose up -d`, I get the error:
```
ERROR: Service 'nextcloud' depends on service 'nextcloud_db' which is undefined.
```
The `docker-compose.yml` file looks like this:
```
version: '3.6'
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
    - 9321:80
    volumes:
    - ./volumes/nextcloud/html:/var/www/html:rw
    restart: unless-stopped
    depends_on:
    - nextcloud_db
    links:
    - nextcloud_db
    networks:
    - iotstack_nw
    - nextcloud_internal
    environment:
    - MYSQL_HOST=nextcloud_db
    - MYSQL_PASSWORD=%randomMySqlPassword%
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    logging:
      options:
        max-size: 5m
        max-file: '3'
networks:
  iotstack_nw:
    name: IOTstack_Net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.16.238.0/24
  iotstack_nw_internal:
    name: IOTstack_Net_Internal
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 192.16.230.0/24
  vpn_nw:
    name: IOTstack_VPN
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.18.200.0/24
  nextcloud_internal:
    name: IOTstack_NextCloud
    driver: bridge
    internal: true
```

To confirm the bug, I removed the `services/` & `volumes/` directories as well as the `docker-compose.yml` file. Then I ran `./menu.sh` again, this time without using the `Options` menu, which created a functioning `docker-compose.yml` including the `nextcloud_db` service. 

Here is the correct `docker-compose.yml`:
```
version: '3.6'
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
    - 9321:80
    volumes:
    - ./volumes/nextcloud/html:/var/www/html:rw
    restart: unless-stopped
    depends_on:
    - nextcloud_db
    links:
    - nextcloud_db
    networks:
    - iotstack_nw
    - nextcloud_internal
    environment:
    - MYSQL_HOST=nextcloud_db
    - MYSQL_PASSWORD=IOtSt4ckmySqlDbPw
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    logging:
      options:
        max-size: 5m
        max-file: '3'
  nextcloud_db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    volumes:
    - ./volumes/nextcloud/db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=IOtSt4ckToorMySqlDb
    - MYSQL_PASSWORD=IOtSt4ckmySqlDbPw
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    restart: unless-stopped
    networks:
    - nextcloud_internal
    logging:
      options:
        max-size: 5m
        max-file: '3'
networks:
  iotstack_nw:
    name: IOTstack_Net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.16.238.0/24
  iotstack_nw_internal:
    name: IOTstack_Net_Internal
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 192.16.230.0/24
  vpn_nw:
    name: IOTstack_VPN
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.18.200.0/24
  nextcloud_internal:
    name: IOTstack_NextCloud
    driver: bridge
    internal: true
```
I then repeated the process again with the 'Randomise..' option and confirmed that the bug happened again. 

EDIT: I also repeated the process chooseing the 'Default...' option and confirmed the bug happens there too. 

I suspect the issue is with either `.templates/nextcloud/build.py` or `.templates/nextcloud/passwords.py`, but I am not able to track it down at the moment. I may take another look at it later if I have a chance. 

I did confirm that not using the `Options` menu successfully, automatically linked 'nextcloud' and 'nextcloud_db', which is a great feature!

*Edited to include .yml file contents, include `docker-compose up -d` error & to correct my previous assumption about how to reproduce the bug (not only happens when using 'Randomize...' option).
