### ISSUE TITLE
Nextcloud-> Error while first login

### ISSUE THREAD

**Issue by Sven2303** [SensorsIot/IOTstack#226]
Hello, since a few days I started to set up Nextcloud according the mentioned video for Andreas and the documentation. But everytime when I try to start working with nextcloud, I run into a failure.

Nextcloud answers my try to initialize and register the admin accout with following message:

_Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'nextcloud.IOTstack_NextCloud' (using password: YES)_ 

I used a fresh Raspberry OS Configuration, used the mentioned command to curl IOTstack from Github, installed docker and docker compose per menue, than I copied Andreas overwrite file, inserted the passwords, removed the wireguard commands, build the stack with mariadb, nextcloud, portainer ce and started docker, everything with the menu.

Maybe one more intersting fact, at the first page of nextcloud, started with Serverip:9321 there is no option to change between the databases, only after the first try to put in username and password, I got the "picture" which is part of the video and the documentation page.

Thanks for all

Best regard
Sven

**Comment by Slyke** [comment]
I'll have my RPi setup in a few days to troubleshoot this (nextcloud doesn't work well on WSL due to file permissions).

In the meantime, can you post your docker-compose.yml file here? I will check over it and run it on my RPi.

**Comment by Sven2303** [comment]
Hello Slyke,
here my compose file:

```
version: '3.6'
services:
  nextcloud:
    volumes:
    - ./volumes/nextcloud/html:/var/www/html


    image: nextcloud
    container_name: nextcloud
    ports:
    - "9321:80"
    restart: unless-stopped
    depends_on:
    - nextcloud_db
    links:
    - nextcloud_db
    networks:
    - iotstack_nw
    - nextcloud_internal
    environment:
    - MYSQL_HOST=nextcloud_db
    - MYSQL_PASSWORD=IOtSt4ckmySqlDbPw       # %randomMySqlPassword% is overwritten during preBuild hook
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    logging:
      options:
        max-size: "5m"
        max-file: "3"
  nextcloud_db:
    environment:
    - MYSQL_ROOT_PASSWORD=_mysql_root_pw_
    - MYSQL_PASSWORD=_mysql_pw_
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud

    image: linuxserver/mariadb
    container_name: nextcloud_db
    volumes:
    - ./volumes/nextcloud/db:/var/lib/mysql
    restart: unless-stopped
    networks:
    - nextcloud_internal
    logging:
      options:
        max-size: "5m"
        max-file: "3"
  mariadb:
    environment:
    - MYSQL_ROOT_PASSWORD=_mysql_root_pw_
    - MYSQL_PASSWORD=_mysql_pw_
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    image: linuxserver/mariadb
    container_name: mariadb
    volumes:
    - ./volumes/mariadb/config:/config
    ports:
    - "3306:3306"
    restart: unless-stopped
    networks:
    - iotstack_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
    - "8000:8000"
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer-ce/data:/data
networks:
  iotstack_nw: # Exposed by your host.
    # external: true
    name: IOTstack_Net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.16.238.0/24
        # - gateway: 192.16.238.1

  iotstack_nw_internal: # For interservice communication. No access to outside
    name: IOTstack_Net_Internal
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 192.16.230.0/24
        # - gateway: 192.16.238.1
  vpn_nw: # Network specifically for VPN
    name: IOTstack_VPN
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.18.200.0/24
        # - gateway: 192.18.200.1

  nextcloud_internal: # Network for NextCloud service
    name: IOTstack_NextCloud
    driver: bridge
    internal: true

  # default:
  #   external: true
  #   name: iotstack_nw

  # hosts_nw:
  #   driver: hosts
```
