### ISSUE TITLE
Environment variables in composer-override.yml doesn't get updated in Docker

### ISSUE THREAD

**Issue by ronnyandre** [SensorsIot/IOTstack#241]
I have updated a container's environment variables, but it doesn't seem like those changes are being reflected in Docker (and Portainer as I use to control the variables).

I have tried to remove the container, rebuild it, removing the container's volume and recreating container. Nothing works. What am I doing wrong?

**Comment by Paraphraser** [comment]
Maybe a bit more detail would help - the contents of your `docker-compose.yml` and `docker-compose.override.yml`, which environment variables you are trying to change for which container.

Your subject line for this issue mis-spells `docker-compose.override.yml`. Is that just an error in the subject line or are you trying to use that file name too?

When you say that it isn't working, how do you know? For example, if I add the following to my NodeRed definition:

```
    environment:
      - RONNYANDRE=ISSUE241
```

then recreate the container (stop, rm, up), and then run

```
$ docker exec nodered bash -c 'echo $RONNYANDRE'
ISSUE241
```

That shows the variable is defined and is being transported inside the container but it means nothing to NodeRed so it does nothing. Maybe the variable you're defining **is** getting into the container but the process inside the container isn't reacting to it. I've mis-typed variable names a couple of times (particularly for InfluxDB where they are tricky to get right).

Anyway, a **lot more information** is likely to get a quicker answer!!

**Comment by ronnyandre** [comment]
Thanks for your feedback. However, I tried exactly what you said, to set evironment variable, ran `docker-compose down CONTAINER`, then `docker-compose rm CONTAINER` and then after changing environment variables, running `docker-compose up -d CONTAINER`. None of the environment variables were changed accordig to my `compose-override.yml` file.

So my actual issue is that the container named `teslamate` cannot connect to my Postgres database container, which is very strange, so I tried to tweak the environment settings.

I see that the changes in `compose-override.yml` isn't reflected in the `docker-override.yml` file, so that may be the issue.

Here is my `compose-override.yml`:

```
services:
  teslamate:
    container_name: teslamate
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=[redacted]
      - DATABASE_PASS=[redacted]
      - DATABASE_NAME=[redacted]
      - DATABASE_HOST=[redacted]
      - MQTT_HOST=[redacted]
      - MQTT_USERNAME=[redacted]
      - MQTT_PASSWORD=[redacted]
    ports:
      - 4000:4000
    volumes:
      - ./volumes/teslamate/import:/opt/app/import
    cap_drop:
      - all
  kanboard:
    container_name: kanboard
    image: kanboard/kanboard:latest
    restart: always
    ports:
      - 8088:80
      - 4433:443
    volumes:
      - ./volumes/kanboard/data:/var/www/app/data
      - ./volumes/kanboard/plugins:/var/www/app/plugins
      - ./volumes/kanboard/ssl:/etc/nginx/ssl
    environment:
      - PLUGIN_INSTALLER=true
```

And my complete `docker-compose.yml`:

```
version: '3.6'
services:
  teslamate:
    container_name: teslamate
    image: teslamate/teslamate:latest
    restart: always
    environment:
    - DATABASE_USER=[redacted]
    - DATABASE_PASS=[redacted]
    - DATABASE_NAME=[redacted]
    - DATABASE_HOST=[redacted]
    - MQTT_HOST=[redacted]
    - MQTT_USERNAME=[redacted]
    - MQTT_PASSWORD=[redacted]
    ports:
    - 4000:4000
    volumes:
    - ./volumes/teslamate/import:/opt/app/import
    cap_drop:
    - all
  kanboard:
    container_name: kanboard
    image: kanboard/kanboard:latest
    restart: always
    ports:
    - 8088:80
    - 4433:443
    volumes:
    - ./volumes/kanboard/data:/var/www/app/data
    - ./volumes/kanboard/plugins:/var/www/app/plugins
    - ./volumes/kanboard/ssl:/etc/nginx/ssl
    environment:
    - PLUGIN_INSTALLER=true
  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
    - "8086:8086"
    - "8083:8083"
    - "2003:2003"
    environment:
    - INFLUXDB_HTTP_FLUX_ENABLED=false
    - INFLUXDB_REPORTING_DISABLED=false
    - INFLUXDB_HTTP_AUTH_ENABLED=false
    - INFLUX_USERNAME=[redacted]
    - INFLUX_PASSWORD=[redacted]
    - INFLUXDB_UDP_ENABLED=false
    - INFLUXDB_UDP_BIND_ADDRESS=0.0.0.0:8086
    - INFLUXDB_UDP_DATABASE=udp
    volumes:
    - ./volumes/influxdb/data:/var/lib/influxdb
    - ./backups/influxdb/db:/var/lib/influxdb/backup
    networks:
    - iotstack_nw

  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    environment:
    - TZ=Etc/UTC
    ports:
    - "1880:1880"
    volumes:
    - ./volumes/nodered/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    devices:
    - "/dev/ttyAMA0:/dev/ttyAMA0"
    - "/dev/vcio:/dev/vcio"
    - "/dev/gpiomem:/dev/gpiomem"
    networks:
    - iotstack_nw
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
    - "8000:8000"
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer-ce/data:/data
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
    - POSTGRES_USER=[redacted]
    - POSTGRES_PASSWORD=[redacted]
    - POSTGRES_DB=[redacted]
    ports:
    - "5432:5432"
    volumes:
    - ./volumes/postgres/data:/var/lib/postgresql/data
    networks:
    - iotstack_nw
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
    - "3000:3000"
    environment:
    - GF_PATHS_DATA=/var/lib/grafana
    - GF_PATHS_LOGS=/var/log/grafana
    volumes:
    - ./volumes/grafana/data:/var/lib/grafana
    - ./volumes/grafana/log:/var/log/grafana
    networks:
    - iotstack_nw

networks:
  iotstack_nw: # Exposed by your host.
    # external: true
    name: IOTstack_Net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.77.60.0/24
        # - gateway: 10.77.60.1

  iotstack_nw_internal: # For interservice communication. No access to outside
    name: IOTstack_Net_Internal
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 10.77.76.0/24
        # - gateway: 10.77.76.1
  vpn_nw: # Network specifically for VPN
    name: IOTstack_VPN
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.77.88.0/24
        # - gateway: 192.18.200.1

  nextcloud_internal: # Network for NextCloud service
    name: IOTstack_NextCloud
    driver: bridge
    internal: true

  # default:
  #   external: true
  #   name: iotstack_nw

  # hosts_nw:
  #   driver: hosts
```
