### ISSUE TITLE
Solution for timescaledb startup failure

### ISSUE THREAD

**Issue by wijnsema** [SensorsIot/IOTstack#287]
Recently the container **timescaledb** stopped working, failing with a segmentation fault. More details can be found at https://github.com/timescale/timescaledb-docker/issues/136

This will effect users creating a new (iot)stack with timescaledb and users updating their stack with docker pull. The problem started with timescale 2.0.1-pg12.

There is still no solution to this issue, but a work around is downgrading to 2.0.0-pg12.

To downgrade, add the following lines to the docker-override.yml file:
```
timescaledb:
    environment: 
    - POSTGRES_PASSWORD=choosepassword
    - POSTGRES_USER=postgres
    image: timescale/timescaledb:2.0.0-pg12
```

After generating the docker file the complete service looks like this:
```
timescaledb:
    environment:
    - POSTGRES_PASSWORD=choosepassword
    - POSTGRES_USER=postgres
    image: timescale/timescaledb:2.0.0-pg12
    container_name: timescaledb
    restart: unless-stopped
    ports:
    - "5432:5432"
    volumes:
    - ./volumes/timescaledb/data:/var/lib/postgresql/data
    networks:
    - iotstack_nw
```

This also solves an earlier issue #232 where the environment variables have a wrong syntax.

Do NOT use the user timescaleuser, this will lead to numerouse errors, just use **POSTGRES_USER=postgres**
