### ISSUE TITLE
grafan .env file missing

### ISSUE THREAD

**Issue by gthessaloniki** [SensorsIot/IOTstack#332]
I switched to the new built but i noticed that this folder is missing ~/IOTstack/services/grafana/grafana.env    . 
Is it the case or i have something misconfigured?

**Comment by Paraphraser** [comment]
I'm not sure what is **meant** to happen at various stages as you switch from old to new menu but the underlying issue is that the old menu design preferences environment files (like grafana.env) while new menu prefers inline environment variables in docker-compose.yml.

You can use either or both (docker-compose - the app - doesn't care). Personally, I run "old menu" because I can't stand the explosion of networks. I prefer the single iotstack_default network. But I have moved all my environment variables into docker-compose.yml because I think it's easier to have everything in the one place rather than spread over multiple files.

I'm not saying the following is "correct" but it works for me:

```
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    environment:
      - TZ=Australia/Sydney
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Somename
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
     #- GF_SERVER_ROOT_URL=http://localhost:3000/grafana
     #- GF_SERVER_SERVE_FROM_SUB_PATH=true
     #- GF_SECURITY_ADMIN_USER=admin
     #- GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
```

The only thing I'm aware of to watch out for is that you should only ever quote the right hand side of an environment variable when it is absolutely essential (eg `VAR="two words"`). In particular, quoting the right hand side of TZ will prevent it from working.
