### ISSUE TITLE
ERROR: Service 'prometheus' depends on service 'cadvisor' which is undefined.

### ISSUE THREAD

**Issue by Melistraza** [SensorsIot/IOTstack#472]
Trying to add *prometheus* for *grafana*.
Added service in *Build Stack* menu and get docker-compose.yml

```
version: '3.6'
services:
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
    - "8000:8000"
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer-ce/data:/data
  prometheus:
    container_name: prometheus
    build: ./.templates/prometheus/.
    restart: unless-stopped
    user: "0"
    ports:
    - "9090:9090"
    environment:
    - IOTSTACK_UID=1000
    - IOTSTACK_GID=1000
    volumes:
    - ./volumes/prometheus/data:/prometheus
    command:
    - '--config.file=/prometheus/config/config.yml'
    #    defaults are:
    #    - --config.file=/etc/prometheus/prometheus.yml
    #    - --storage.tsdb.path=/prometheus
    #    - --web.console.libraries=/usr/share/prometheus/console_libraries
    #    - --web.console.templates=/usr/share/prometheus/consoles
    depends_on:
    - cadvisor
    - nodeexporter
    networks:
    - iotstack_nw

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
    - "3000:3000"
    environment:
    - GF_PATHS_DATA=/var/lib/grafana
    - GF_PATHS_LOGS=/var/log/grafana
    volumes:
    - ./volumes/grafana/data:/var/lib/grafana
    - ./volumes/grafana/log:/var/log/grafana
    networks:
    - iotstack_nw

networks:
  iotstack_nw: # Exposed by your host.
    # external: true
    name: IOTstack_Net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.77.60.0/24
        # - gateway: 10.77.60.1

  iotstack_nw_internal: # For interservice communication. No access to outside
    name: IOTstack_Net_Internal
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 10.77.76.0/24
        # - gateway: 10.77.76.1
  vpn_nw: # Network specifically for VPN
    name: IOTstack_VPN
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.77.88.0/24
        # - gateway: 192.18.200.1

  nextcloud_internal: # Network for NextCloud service
    name: IOTstack_NextCloud
    driver: bridge
    internal: true

  # default:
  #   external: true
  #   name: iotstack_nw

  # hosts_nw:
  #   driver: hosts
```

Running *Docker Commands* > *Restart stack* and get

```
Restarting Stack...
Stop Stack:
docker-compose down
ERROR: Service 'prometheus' depends on service 'cadvisor' which is undefined.

Start Stack:
docker-compose up -d --remove-orphans
ERROR: Service 'prometheus' depends on service 'cadvisor' which is undefined.

Stack Restarted
Process terminated. Press [Enter] to show menu and continue.
```

according to this config lines
```
depends_on:
    - cadvisor
    - nodeexporter
```
this two services also should be added to docker-compose.yml
but they missed.

Using latest version of IOTstack:
```
git fetch
git pull
Already up to date.
```

Found article:
https://sensorsiot.github.io/IOTstack/Containers/Prometheus/#dependencies
