### ISSUE TITLE
Simple Samba share

### ISSUE THREAD

**Issue by Nurgak** [SensorsIot/IOTstack#548]
I was looking around to share some media over Samba, but I could not find a good example on how to set it up.

With some effort I was able to achieve what I wanted: read-only shares with guest account for movies/series...

The goal was to stream movies to an Apple TV device. My method so far was to use the *TV* app on MacOS, which could only stream mp4 files and no subtitles to the *Computers* app on the Apple TV, very limited...

With Samba shares enabled and the *VLC* app installed on Apple TV any movie can be streamed and subtitles are an option as long as the subtitle file name is the same as the media file name.

Moreover, my media is stored on an external device, hosting IOTstack, inside the Nextcloud volume.

Here's my example.
```yml
version: '3.6'
services:
  samba:
    container_name: samba
    image: dperson/samba
    ports:
    - "139:139"
    - "445:445"
    read_only: true
    volumes:
    - type: bind
      source: /media/pi/storage/IOTstack/volumes/nextcloud/html/data/nurgak/files
      target: /share
      read_only: true
    restart: unless-stopped
    command: '-s "Movies;/share/Movies" -s "Series;/share/Series"'
```

Perhaps it could be interesting to integrate to IOTstack? I'm not sure what half of the options do...

**Comment by ukkopahis** [comment]
Samba is certainly useful in quite many scenarios. On the other hand it doesn't feel like an internet-of-things application. But that isn't really a strict requirement.

* Latest released version of dperson/samba is [vulnerable](https://github.com/dperson/samba/issues/407) This could fixed by building a new image directly using the github sources, but the entrypoint script doesn't work with new smbd versions. Looking at forks of this repository I found https://github.com/jtagcat/samba, which has automatically builds a new weekly release using alpine:3. It seems to at least start:

``` yaml
version: '3.6'
services:
  samba:
    container_name: samba
    image: ghcr.io/jtagcat/samba:samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - ./volumes/samba/share:/share:ro
    restart: unless-stopped
    command: '-s "share;/share"'

```
