### ISSUE TITLE
Wishlist: ioBroker Support

### ISSUE THREAD

**Issue by mooseDev** [SensorsIot/IOTstack#552]
Please add ioBroker to the list. Thx

**Comment by Paraphraser** [comment]
Seems straightforward enough. Try this:

```
  iobroker:
    container_name: iobroker
    image: buanet/iobroker
#   hostname: iobroker
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
    - SETGID=1000
    - SETUID=1000
    ports:
      - "8084:8081"
    volumes:
      - ./volumes/iobroker:/opt/iobroker

```

External ports 8081..8083 already used by other templates. 8084 is first free in that sequence.

Not sure about the purpose of hostname. I know what it does. I just don't see the point in this context. That's why I've commented it out.

Included the uid/gid so you can give it "the treatment" once you settle on what that should be.

Seems to be "well behaved" - self initialises persistent storage. All owned by pi.
