### ISSUE TITLE
Support for ring-mqtt

### ISSUE THREAD

**Issue by basil-dsouza** [SensorsIot/IOTstack#632]
Has anyone considered adding ring-mqtt support into IOTStack?  Based on my limited knowledge of IOTStack, it seems like it should be possible to integrate this: https://github.com/tsightler/ring-mqtt/wiki/Installation-(Docker)
```
  ring-mqtt:
    container_name: ring-mqtt
    restart: unless-stopped
    image: tsightler/ring-mqtt
    ports:
      - 8554:8554                      # Enable RTSP port for external media player access
    volumes:
      - <host_path>:/data           # Mapping of local folder to provide persistent storage
    logging:                           #limit logs to 10m and 3 files
      options:
        max-size: 10m
        max-file: "3"

```

Am interested in hearing if anyone has already tried this? or if anyone is interested in trying it?
I know enough docker to add this locally to my docker-compose file and try to get it working, but do not know enough IOTStack to integrate this well into the menu system.
