### ISSUE TITLE
Mosquitto security does not persist

### ISSUE THREAD

**Issue by Paraphraser** [SensorsIot/IOTstack#68]
# Mosquitto security does not persist

## Problem

After working through the documentation on how to set up a username and password for Mosquitto, I have found that it "works" but is not persistent.

Rather than just prepare a pull request, I wanted to draw attention to the security issue in case my proposed solution raises red flags for anyone.

The basic problem is that the internal container path for the password file is not mapped to any external path in the template `service.yml` and, therefore, not in the `docker-compose.yml` and not anywhere in the scope of `~/IOTstack/volumes/mosquitto`.

As soon as the container is rebuilt, the internal password file disappears and the container constantly restarts until you disable the line in `mosquitto.conf` that enables password checking.

I do not understand why this problem hasn't been reported before. The only mention I can find is:

* [gcgarner/IOTstack issue 32](https://github.com/gcgarner/IOTstack/issues/32)

but that is about a path inconsistency.

## Discussion

At the moment, the mosquitto template `service.yml` looks like this:

```
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "1883"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./services/mosquitto/filter.acl:/mosquitto/config/filter.acl
```

Given the documented command for creating a password:

```
mosquitto_passwd -c /mosquitto/config/pwfile MYUSER
```

The obvious solution would be another volumes mapping like:

```
      - ./volumes/mosquitto/pwfile:/mosquitto/config/pwfile
```

I am not a great fan of volume-mapping **files**. They can be pernickety and a bit restrictive. I prefer mapping **directories**.

## Proposed solution

1. Add this volume mapping to the template `service.yml`:

	```
	- ./volumes/mosquitto/pwfile:/mosquitto/pwfile
	```

2. Add this line to the template `directoryfix.sh`:

	```
	sudo mkdir -p ./volumes/mosquitto/pwfile/
	```
	
3. Change the relevant line in the template `mosquitto.conf` to read:

	```
	#password_file /mosquitto/pwfile/pwfile
	```

4. Change the documentation so that the command reads:

	```
	mosquitto_passwd -c /mosquitto/pwfile/pwfile «MYUSER»
	```
