### ISSUE TITLE
Change deconz web-socket port, currently 443

### ISSUE THREAD

**Issue by TomTom101** [SensorsIot/IOTstack#748]
I'd like to change the default `ws-port` of deconz which by default is set to 443 – a imo terrible choice ;) – and play nice with Home Assistant.

HA documentation says:
> The deCONZ integration uses the WebSocket port provided by the deCONZ REST API. If you’re running the deCONZ Docker container **make sure that it properly configures the WebSocket port** so deCONZ can report what port is exposed outside of the containerized environment.
https://www.home-assistant.io/integrations/deconz/

Whatever "properly configure" means, I tried to map port 8443:443 in the docker compose and set the `DECONZ_WS_PORT` to 8443, hoping this would report, which port is used "outside of the containerized environment". However, HA still complains about the WS port not found.
I want to avoid making any changes inside the container in order to having having to patch things after updates.

Any ideas how to accomplish that?

PS.: I want to add https-portal, maybe also a nice addition to IoTStack!?

**Comment by Paraphraser** [comment]
Well, I hope you don't mind but I'll start by responding to your editorialising with some of my own.

Other than not playing nice with HA, you didn't really elaborate on *why* you thought 443 was a poor choice. That kind of *practical* knowledge is "good stuff" for adding to the IOTstack doco.

I don't use `deconz` so I can't comment on the *practical* aspects of port choice but:

1. It's been port 443 in IOTstack since `deconz` was added in Feb 2020 (ie you're the first to raise this); and
2. Port 443 is what's recommended in the `deconz` documentation:

	- [DockerHub](https://hub.docker.com/r/deconzcommunity/deconz)
	- [GitHub](https://github.com/deconz-community/deconz-docker)

Even if `deconz` were only being added to IOTstack for the first time today, 443 would at least gain *consideration* if, perhaps not, *implementation* for the simple reason that the AdGuardHome service definition also claims 443.

In other words, right now, 443 is currently being used by both `deconz` and AdGuardHome. All by itself that's a reason (at least for me) to agree that something should be done to resolve that conflict.

No other service definition is currently using 8443 so it's as good a choice as any.

As I read the `deconz` documentation, I think the default service definition will need to look like this:

``` yaml
deconz:
  image: deconzcommunity/deconz
  container_name: deconz
  restart: unless-stopped
  ports:
    - "8090:80"
    - "8443:8443"
    - "5901:5900"
  volumes:
    - ./volumes/deconz:/opt/deCONZ
  devices:  # This list is replaced during the build process. Modify the list in "build_settings.yml" to change it.
    - /dev/null
  environment:
    - DECONZ_VNC_MODE=1
    - DECONZ_VNC_PASSWORD=%randomPassword%
    - DEBUG_INFO=1
    - DEBUG_APS=0
    - DEBUG_ZCL=0
    - DEBUG_ZDP=0
    - DEBUG_OTAU=0
    - DECONZ_WS_PORT=8443
```
	
Two changes are needed:

1. Add the `DECONZ_WS_PORT` environment variable. That instructs the **container** to listen on **internal** port 8443.
2. Map **external** port 8443 to **internal** port 8443 so that NAT will cause the host to listen on port 8443 and forward to the container's port 8443.

If you can give those changes a try and see if it works, we can think about moving to a pull request to make this the default.
