### ISSUE TITLE
Port conflict between heimdall and zigbee2mqtt_assistant (8880)

### ISSUE THREAD

**Issue by nfelger** [SensorsIot/IOTstack#751]
Both containers seem to want to use port 8880. I'm new to IOTStack, so maybe I missed an option to configure ports (but I thought they should be conflict-free out-of-the-box).

Can we change one of them? Or is there another way I can fix this?

```yaml
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - ./volumes/heimdall/config:/config
    ports: 
    - 8880:80
    - 8883:443
    restart: unless-stopped
  ...
  zigbee2mqtt_assistant:
    container_name: zigbee2mqtt_assistant
    image: carldebilly/zigbee2mqttassistant
    restart: unless-stopped
    ports:
    - "8880:80"
    environment:
    - VIRTUAL_HOST=~^zigbee2mqtt_assistant\..*\.xip\.io
    - Z2MA_SETTINGS__MQTTSERVER=mosquitto
    - VIRTUAL_PORT=8880
```
