### ISSUE TITLE
Error message from Transmission when trying to compose up

### ISSUE THREAD

**Issue by ApricotFarm** [SensorsIot/IOTstack#91]
After running menu.sh setup, I immediately ran `docker-compose up -d` as suggested in the instructions. I received the following error message:

```
pi@raspberrypi:~/IOTstack $ docker-compose up -d
ERROR: Named volume "transm_config_volume:/config:rw" is used in service "transmission" but no declaration was found in the volumes section.
```

I'm too much of a Docker noob to know how to get in and tinker with this, so I'm afraid I can't provide much insight as to why this is happening. I couldn't find any documentation to fall back to; it looks like the Transmission container is a recent experimental addition to the stack.

**Comment by Paraphraser** [comment]
On a Docker-noob scale of 1..10, I might be at 1.01. I also don't use `transmission` so I'm stuck at zero on that noob scale. However, I'll try to give you some pointers based on what I would try if I struck a problem like this.

You can also help by going into `~/IOTstack/docker-compose.yml` and finding the chunks that look like this:

##### *Chunk 1:*

```
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - transm_config_volume:/config
      - transm_download_volume:/downloads
      - transm_watch_volume:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped
```

##### *Chunk 2:*

```
  transm_download_volume:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: .volumes/transmission/downloads

  transm_watch_volume:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: .volumes/transmission/watch

  transm_config_volume:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: .volumes/transmission/config
```

### Check 1

If what is in your `docker-compose.yml` looks different then please append the relevant chunks of your `docker-compose.yml` to this issue.

### Check 2

If you see both chunks then I suspect that the problem is that each "device" line in chunk 2 is mal-formed. The first one looks like this:

```
       device: .volumes/transmission/downloads
```

but should probably look like this (see "More discussion" below for an explanation):

```
       device: ./volumes/transmission/downloads
```

For all three `device:` lines I'd insert a "/" after the "." then save `docker-compose.yml` and try running `docker-compose up -d` again.

If that fixes the problem then please confirm it.

### Check 3

If you see chunk 1 but not chunk 2, that suggests something is wrong with the process for generating `docker-compose.yml`.

What I would do is to copy the contents of:

```
~/IOTstack/.templates/transmission/volumes.yml
```

to the clipboard, then paste them into `docker-compose.yml`, then try again. If that didn't work then I'd repeat Check 2 because I'm *reasonably* sure `.volumes` should be `./volumes`.

If either of those fix the problem then, again, please confirm it.

### Discussion

When I do this:

```
$ find ~/IOTstack/.templates -name "*.yml"
``` 

I get this result:

```
/home/pi/IOTstack/.templates/grafana/service.yml
/home/pi/IOTstack/.templates/python/service.yml
/home/pi/IOTstack/.templates/mariadb/service.yml
/home/pi/IOTstack/.templates/rtl_433/service.yml
/home/pi/IOTstack/.templates/homebridge/service.yml
/home/pi/IOTstack/.templates/plex/service.yml
/home/pi/IOTstack/.templates/transmission/volumes.yml
/home/pi/IOTstack/.templates/transmission/service.yml
/home/pi/IOTstack/.templates/zigbee2mqtt/service.yml
/home/pi/IOTstack/.templates/openhab/service.yml
/home/pi/IOTstack/.templates/mosquitto/service.yml
/home/pi/IOTstack/.templates/dozzle/service.yml
/home/pi/IOTstack/.templates/nextcloud/service.yml
/home/pi/IOTstack/.templates/portainer/service.yml
/home/pi/IOTstack/.templates/pihole/service.yml
/home/pi/IOTstack/.templates/blynk_server/service.yml
/home/pi/IOTstack/.templates/nodered/service.yml
/home/pi/IOTstack/.templates/telegraf/service.yml
/home/pi/IOTstack/.templates/adminer/service.yml
/home/pi/IOTstack/.templates/tasmoadmin/service.yml
/home/pi/IOTstack/.templates/motioneye/service.yml
/home/pi/IOTstack/.templates/webthings_gateway/service.yml
/home/pi/IOTstack/.templates/diyhue/service.yml
/home/pi/IOTstack/.templates/espruinohub/service.yml
/home/pi/IOTstack/.templates/influxdb/service.yml
/home/pi/IOTstack/.templates/deconz/service.yml
/home/pi/IOTstack/.templates/deconz/service_raspbee.yml
/home/pi/IOTstack/.templates/deconz/service_conbee.yml
/home/pi/IOTstack/.templates/deconz/service_conbee_II.yml
/home/pi/IOTstack/.templates/postgres/service.yml
/home/pi/IOTstack/.templates/gitea/service.yml
/home/pi/IOTstack/.templates/timescaledb/service.yml
```

In that list, `transmission` is the only example with a `volumes.yml` file. For me, that raises two questions:

1. Are the contents of `volumes.yml` making it into `docker-compose.yml` (ie as chunk 2)?
2. If they are, are the contents of `volumes.yml` in the right place inside `docker-compose.yml`?

### Check 4

Check 3 deals with Q1. Q2 is because I have no idea how `docker-compose.yml` is parsed or whether order is important. In other words, if I saw this error and the answer to Q1 was "yes" but the contents of `volumes.yml` appeared **after** the contents of `service.yml` then I might try rearranging the order in `docker-compose.yml` to see if it made a difference.

If you get to this point and re-ordering works then that suggests a problem with the build process so please confirm the result.

### More discussion

After that, I'd look at the other examples in `docker-compose.yml` (eg `mosquitto`) and observe this kind of pattern:

```
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./volumes/mosquitto/pwfile:/mosquitto/pwfile
      ...
```

Each line beginning with a dash is split into two parts about the colon. The right hand side is a path **inside** the container while the left hand side is the path **outside** the container where the leading "." implies *relative to the folder where `docker-compose.yml` is located*.

Decomposing the first one as an example, the path `/mosquitto/data` **inside** the container is mapped to:

```
./volumes/mosquitto/data
```

**outside** the container, which expands to the absolute path:

```
/home/pi/IOTstack/volumes/mosquitto/data
```

What your error seems to be suggesting is:

```
transm_config_volume:/config
```

**should** be being substituted as EITHER:

* if `volumes.yml` is interpreted "as is":

	```
	.volumes/transmission/config:/config
	```

* OR, if `volumes.yml` is hand-edited to replace `.volumes` with `./volumes`'

	```
	./volumes/transmission/config:/config
	```

but isn't, which is what makes me wonder if the whole `volumes.yml` is either missing, or is in the wrong place in `docker-compose.yml`, or has the missing "/" problem.

### Check 5

What I would do next is try to stitch together a solution for `transmission` that followed the pattern established by every other container type. So:

```
    volumes:
      - transm_config_volume:/config
      - transm_download_volume:/downloads
      - transm_watch_volume:/watch
```

would become:

```
    volumes:
      - ./volumes/transmission/config:/config
      - ./volumes/transmission/downloads:/downloads
      - ./volumes/transmission/watch:/watch
```

I'd also double-check that:

```
~/IOTstack/.templates/transmission/build.sh
```

had been run. It creates the three folders inside `.volumes/transmission` but I think those need to be there before `docker-compose` is run.

I hope something in this helps....
